<?php

namespace Beejee\App\Controllers;

use Beejee\App\Core\Classes\Auth;
use Beejee\App\Core\Classes\Str;
use Beejee\App\Core\Controller;
use Rakit\Validation\Validator;

class LoginController extends Controller
{
    function actionIndex()
    {
        parent::actionIndex(); // TODO: Change the autogenerated stub
    }

    function actionAuth()
    {
        $validator = new Validator();

        $validation = $validator->make($_POST, [
            "login"=>"required",
            "password"=>"required",
        ]);

        $validation->validate();

        if ($validation->fails()) {
            $this->view->generateJson($validation->errors(), "Validation Error!", false);
            return;
        }

        $data = $validation->getValidData();

        if (!Auth::auth($data["login"], $data["password"])) {
            $this->view->generateJson([], "Auth error: login or password not valid!", false);
            return;
        }

        $this->view->generateJson([], "Authorization success!");
    }

    function actionLogout()
    {
        Auth::logout();
        $this->view->generateJson([], "Logout success");
    }
}